"""
Gmail SMTP provider - the current MVP implementation of the email
abstraction.

This is the ONLY module in the application that imports `smtplib` for
outbound email. The auth service calls `src.email.service.send_email`,
which dispatches to `send_via_gmail_smtp` here. Replacing this provider
with SendGrid, SES, Postmark, or any other service is a change to this
module and the settings that feed it - no authentication code changes.

Gmail SMTP constraints (see .env.example for the operator-facing form):

  * The sending Google account MUST have 2-Step Verification enabled.
  * Authentication uses an APP PASSWORD, not the account password. An
    app password is a 16-character token generated by Google for a
    specific application; it can be revoked without changing the
    account password.
  * Gmail imposes daily sending limits (a few hundred per day for a
    personal account; lower for a fresh account).
  * Deliverability and reputation are weaker than a dedicated
    transactional email provider. Messages may be throttled or filtered,
    especially at volume.

This provider is intended for MVP and low-volume use. It is NOT the
long-term production email infrastructure.

Security posture:
  * The app password is read from `settings.smtp_password` and is never
    written to a log line, an exception message, or an API response.
  * Failure messages from smtplib are reduced to the exception class
    name; the provider's response text is discarded.
  * Only the recipient's domain is logged, never the local part.
  * The message body is never logged - later auth emails will carry
    OTPs, password-reset links, and email-verification links.
"""
from __future__ import annotations

import smtplib
from email.message import EmailMessage
from email.policy import default as _default_policy

from src.config.settings import settings
from src.email.exceptions import EmailDeliveryError, EmailNotConfigured
from src.utils.logger import get_logger

logger = get_logger(__name__)


_PROVIDER_NAME = "gmail_smtp"

# Bounded socket timeout for connecting to the SMTP server. Kept as a
# module constant rather than a setting: it is a property of the
# transport, not of the deployment's business policy, and adding a
# setting for it would duplicate what `settings.timeout_seconds`
# already covers at a different layer. 15 seconds is comfortably longer
# than any realistic handshake and short enough that a hung connection
# does not stall a request indefinitely.
_CONNECT_TIMEOUT_SECONDS = 15


def _recipient_domain(to: str) -> str:
    """Return the domain portion of a recipient address for logging.

    Deliberately never returns the local part. `"alice@example.com"`
    becomes `"example.com"`; a malformed value with no `@` becomes the
    literal string `"invalid"` so a log line always carries a
    categorically-useful value rather than a truncated one.
    """
    if "@" not in to:
        return "invalid"
    domain = to.rsplit("@", 1)[-1].strip()
    return domain or "invalid"


def _require_configured() -> None:
    """Raise EmailNotConfigured if SMTP is not fully configured.

    settings.py validates this at startup when EMAIL_DELIVERY_ENABLED is
    True, so in a correctly configured deployment this never fires. It
    is checked here as well because:
      * the setting can be flipped at runtime (by tests, or by a future
        hot-reload path), and
      * a caller invoking this provider directly (bypassing the
        abstraction) should get the same clear error rather than an
        AttributeError on None.
    """
    if not getattr(settings, "email_delivery_enabled", False):
        raise EmailNotConfigured(
            "Email delivery is disabled (EMAIL_DELIVERY_ENABLED is false)."
        )
    missing: list[str] = []
    if not settings.smtp_host:
        missing.append("smtp_host")
    if not settings.smtp_username:
        missing.append("smtp_username")
    if not settings.smtp_password:
        missing.append("smtp_password")
    if not settings.smtp_from_address:
        missing.append("smtp_from_address")
    if missing:
        raise EmailNotConfigured(
            "SMTP configuration is incomplete: " + ", ".join(missing) + "."
        )


def _build_message(to: str, subject: str, body: str) -> EmailMessage:
    """Construct a standard plain-text MIME message.

    Uses `email.message.EmailMessage` with `email.policy.default`,
    which handles RFC 2047 encoding for a non-ASCII Subject header and
    UTF-8 body encoding with an appropriate Content-Transfer-Encoding.
    No raw SMTP protocol commands are built by hand anywhere in this
    module.
    """
    message = EmailMessage(policy=_default_policy)
    message["From"] = settings.smtp_from_address
    message["To"] = to
    message["Subject"] = subject
    message.set_content(body, subtype="plain", charset="utf-8")
    return message


def _deliver(message: EmailMessage) -> None:
    """Open a connection and hand the message to Gmail's SMTP server.

    Branches on the TLS/SSL mode exactly as `settings` validated it:
    `smtp_use_ssl=True` uses implicit TLS (`SMTP_SSL`), otherwise the
    connection is opened in the clear and upgraded via `starttls()` when
    `smtp_use_tls=True`. The two settings are mutually exclusive and at
    least one is required when email delivery is enabled (enforced at
    settings load), so exactly one branch is taken in practice.

    `ehlo()` is called explicitly both before and after STARTTLS. The
    pre-STARTTLS EHLO is required because some servers do not advertise
    the STARTTLS extension until they see it; the post-STARTTLS EHLO is
    required because the server's capabilities (and any SASL mechanisms
    used by `login()`) can change after the TLS upgrade.
    """
    host = settings.smtp_host
    port = settings.smtp_port

    if settings.smtp_use_ssl:
        # Implicit TLS - the connection is encrypted from the first byte.
        with smtplib.SMTP_SSL(
            host, port, timeout=_CONNECT_TIMEOUT_SECONDS
        ) as connection:
            connection.login(settings.smtp_username, settings.smtp_password)
            connection.send_message(message)
    else:
        # Plain connection, optionally upgraded to TLS via STARTTLS.
        with smtplib.SMTP(
            host, port, timeout=_CONNECT_TIMEOUT_SECONDS
        ) as connection:
            connection.ehlo()
            if settings.smtp_use_tls:
                connection.starttls()
                connection.ehlo()
            connection.login(settings.smtp_username, settings.smtp_password)
            connection.send_message(message)


def send_via_gmail_smtp(to: str, subject: str, body: str) -> None:
    """Deliver a plain-text email via Gmail SMTP.

    Raises:
        EmailNotConfigured: email_delivery_enabled is false, or the SMTP
            settings required to connect are missing.
        EmailDeliveryError: the connection, login, or send failed. The
            message names only the failure class; no credentials, no
            provider response text, and no body content are included.
    """
    # Defensive check on the recipient. The abstraction validates this
    # too, but a caller invoking the provider directly should not be able
    # to reach the SMTP layer with an empty To header.
    if not isinstance(to, str) or not to.strip():
        raise EmailDeliveryError("Recipient address is empty or invalid.")

    _require_configured()

    message = _build_message(to, subject, body)

    try:
        _deliver(message)
    except (smtplib.SMTPException, OSError) as e:
        # Covers every failure smtplib can raise: connection errors,
        # TLS negotiation failures, authentication failures (a subclass
        # of SMTPException), and command rejections. OSError covers DNS
        # failures and socket timeouts that occur before smtplib wraps
        # them.
        logger.warning(
            "Email delivery failed",
            provider=_PROVIDER_NAME,
            recipient_domain=_recipient_domain(to),
            failure_class=type(e).__name__,
        )
        # `from None` suppresses the original exception's traceback so
        # the chained SMTP response text does not leak through the
        # rendered traceback. Only the exception class name is carried
        # into the message.
        raise EmailDeliveryError(
            f"SMTP delivery failed ({type(e).__name__})."
        ) from None
    else:
        logger.info(
            "Email delivered",
            provider=_PROVIDER_NAME,
            recipient_domain=_recipient_domain(to),
        )


__all__ = ["send_via_gmail_smtp"]