"""add project_memories table for per-project agent knowledge

Revision ID: 0ecbf2b6f9e6
Revises: 3a6e2d1c8f4b
Create Date: 2026-09-09 09:46:17.530215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ecbf2b6f9e6'
down_revision: Union[str, Sequence[str], None] = '3a6e2d1c8f4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_memories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('entry_metadata', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_memories_category'), 'project_memories', ['category'], unique=False)
    op.create_index(op.f('ix_project_memories_created_at'), 'project_memories', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_memories_session_id'), 'project_memories', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_memories_session_id'), table_name='project_memories')
    op.drop_index(op.f('ix_project_memories_created_at'), table_name='project_memories')
    op.drop_index(op.f('ix_project_memories_category'), table_name='project_memories')
    op.drop_table('project_memories')
    # ### end Alembic commands ###
