"""add project_documents table for uploaded consultant documents

Revision ID: 536867117b89
Revises: d28bffc96920
Create Date: 2026-09-11 10:43:43.904155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '536867117b89'
down_revision: Union[str, Sequence[str], None] = 'd28bffc96920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('extracted_text_chars', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_project_documents_session_id'), 'project_documents', ['session_id'], unique=False)
    op.create_index(op.f('ix_project_documents_uploaded_at'), 'project_documents', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_project_documents_user_id'), 'project_documents', ['user_id'], unique=False)
    op.create_index(op.f('ix_process_steps_requirement_id'), 'process_steps', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_solution_decisions_requirement_id'), 'solution_decisions', ['requirement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solution_decisions_requirement_id'), table_name='solution_decisions')
    op.drop_index(op.f('ix_process_steps_requirement_id'), table_name='process_steps')
    op.drop_index(op.f('ix_project_documents_user_id'), table_name='project_documents')
    op.drop_index(op.f('ix_project_documents_uploaded_at'), table_name='project_documents')
    op.drop_index(op.f('ix_project_documents_session_id'), table_name='project_documents')
    op.drop_table('project_documents')
    # ### end Alembic commands ###
