"""
Password hashing, JWT access-token helpers, and security primitives
used by the authentication service layer.

Passwords
---------
Hashing uses bcrypt directly (not passlib). Bcrypt has a hard 72-byte
input limit; longer passwords are truncated to that, which matches
bcrypt's own internal behavior.

The work factor is pinned explicitly via `_BCRYPT_DEFAULT_ROUNDS` rather
than relying on bcrypt's implicit default. bcrypt currently defaults to
12, so this is not a hash-format change and no existing hash is
invalidated - it just makes a security-sensitive value visible in the
source and immune to a library default change.

Access tokens
-------------
A single short-lived access token per login, HMAC-signed (HS256) with
JWT_SECRET_KEY. The signing algorithm is fixed at import time and
validated against a small allowlist. It is NEVER read from the token
header (which would enable `alg: none` and RSA/HMAC confusion attacks).
PyJWT's `algorithms=[...]` option is what enforces this - the module
never passes `algorithms=None` or an empty list.

Claims:
    sub   Subject - the user's id. Required, must be a non-empty string.
    exp   Expiry - required; decode rejects tokens without it.
    iat   Issued-at - set on every new token.
    jti   JWT id - unique per token; enables per-token denylisting later.

Opaque tokens (refresh, password reset, email verification)
-----------------------------------------------------------
These are cryptographically random URL-safe strings generated by
`generate_secure_token()`. The raw value is delivered to the client
once (as a cookie or in an emailed link) and is NEVER persisted - only
its SHA-256 hex digest is stored, via `hash_token()`.

SHA-256 is used rather than bcrypt for these values because the
underlying secrets are cryptographically random with sufficient entropy
that the deliberate slowness of password hashing is unnecessary, and
adding that latency to every refresh and verification would be a
material cost with no security gain. Passwords continue to use bcrypt.

OTP codes
---------
Numeric OTPs are generated one digit at a time using
`secrets.randbelow(10)` - a cryptographically secure source - rather
than a pseudo-random function, and are never a sequence or timestamp.
Only the SHA-256 digest of the code is persisted.
"""
from __future__ import annotations

import hashlib
import secrets
import uuid
from datetime import datetime, timedelta, timezone
from typing import Optional

import bcrypt
import jwt

from src.config.settings import settings
from src.utils.logger import get_logger

logger = get_logger(__name__)


# ---------------------------------------------------------------------------
# Password hashing
# ---------------------------------------------------------------------------
_BCRYPT_MAX_BYTES = 72
_BCRYPT_DEFAULT_ROUNDS = 12


def hash_password(
    plain_password: str,
    *,
    rounds: Optional[int] = None,
) -> str:
    """Hash a password with bcrypt.

    The `rounds` parameter is optional and intended for tests - production
    callers should leave it None to use the pinned default cost factor
    (`_BCRYPT_DEFAULT_ROUNDS`, currently 12).

    Making the default explicit does not change any existing hash: bcrypt
    has always defaulted to 12, so a hash produced before this change
    verifies identically after it. No password rehash is required.
    """
    if not isinstance(plain_password, str):
        raise TypeError("plain_password must be a string")
    truncated = plain_password.encode("utf-8")[:_BCRYPT_MAX_BYTES]
    effective_rounds = rounds if rounds is not None else _BCRYPT_DEFAULT_ROUNDS
    salt = bcrypt.gensalt(rounds=effective_rounds)
    return bcrypt.hashpw(truncated, salt).decode("utf-8")


def verify_password(plain_password: str, hashed_password: str) -> bool:
    """Constant-time password verification. Returns False (never raises)
    on any malformed input - a bad hash row must not crash a login attempt
    into a 500."""
    if not isinstance(plain_password, str) or not isinstance(hashed_password, str):
        return False
    truncated = plain_password.encode("utf-8")[:_BCRYPT_MAX_BYTES]
    try:
        return bcrypt.checkpw(truncated, hashed_password.encode("utf-8"))
    except (ValueError, TypeError):
        # Malformed hash, wrong prefix, truncated base64 - all client
        # errors in practice. Do not let them become 500s.
        return False


# ---------------------------------------------------------------------------
# Secure random generation
# ---------------------------------------------------------------------------
# Default token length. 32 bytes = 256 bits of entropy, encoded by
# `secrets.token_urlsafe` as 43 URL-safe characters. This is comfortably
# above any practical brute-force threshold.
_DEFAULT_TOKEN_BYTES = 32
_MIN_TOKEN_BYTES = 16

# Bounds for OTP length. The lower bound prevents a uselessly short code;
# the upper bound prevents a code longer than any practical SMS/email
# flow would present, and keeps the search space within the range where
# attempt limits + short expiry are the effective control.
_MIN_OTP_LENGTH = 4
_MAX_OTP_LENGTH = 10


def generate_secure_token(nbytes: int = _DEFAULT_TOKEN_BYTES) -> str:
    """Return a cryptographically random URL-safe token string.

    Uses Python's `secrets` module, which is the OS-backed CSPRNG
    (`os.urandom` on POSIX, `CryptGenRandom`/`BCryptGenRandom` on
    Windows). `random.random()`, `uuid.uuid4()` alone, timestamps, and
    counters are deliberately not used.

    Used for: refresh tokens, password-reset tokens, email-verification
    tokens, and any pending-authentication credential that the service
    layer decides to generate rather than store server-side.

    Entropy: `nbytes * 8` bits. The default (32 bytes → 256 bits) is far
    above any practical brute-force threshold. `_MIN_TOKEN_BYTES`
    prevents a caller from accidentally requesting a short token.
    """
    if not isinstance(nbytes, int) or nbytes < _MIN_TOKEN_BYTES:
        raise ValueError(
            f"nbytes must be an int >= {_MIN_TOKEN_BYTES} "
            f"(got {nbytes!r}); smaller values do not provide adequate "
            "entropy for an authentication credential."
        )
    return secrets.token_urlsafe(nbytes)


def generate_otp(length: int) -> str:
    """Return a numeric OTP of exactly `length` digits.

    Each digit is drawn independently from `secrets.randbelow(10)`, which
    uses the same OS-backed CSPRNG as `generate_secure_token`. Digits are
    zero-padded by construction (the value is built as a string, so a
    leading zero is preserved).

    Not a sequence, not a timestamp, not derived from any user-supplied
    value or from a value visible to an attacker.
    """
    if not isinstance(length, int) or length < _MIN_OTP_LENGTH or length > _MAX_OTP_LENGTH:
        raise ValueError(
            f"length must be an int between {_MIN_OTP_LENGTH} and "
            f"{_MAX_OTP_LENGTH} (got {length!r})."
        )
    return "".join(str(secrets.randbelow(10)) for _ in range(length))


# ---------------------------------------------------------------------------
# Token hashing and comparison
# ---------------------------------------------------------------------------
def hash_token(raw: str) -> str:
    """Return the SHA-256 hex digest of a token or OTP code.

    Deterministic: the same input always produces the same digest, which
    is what allows a request that presents a token to be resolved by a
    single indexed lookup on the stored `*_hash` column.

    Used for: refresh-token hashes, password-reset token hashes,
    email-verification token hashes, and OTP code hashes. The same
    function is used for all four because the underlying values are all
    high-entropy (or, for OTPs, protected by attempt limits and a short
    expiry) and the digest is not a password-storage mechanism.

    The raw value is never logged, never persisted, and never compared
    against anything by this function - it only produces the digest.
    Callers compare digests with `constant_time_equal`.
    """
    if not raw or not isinstance(raw, str):
        raise ValueError("raw token must be a non-empty string")
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def constant_time_equal(a: str, b: str) -> bool:
    """Constant-time string comparison for secret-derived values.

    Wraps `secrets.compare_digest`, which runs in time independent of the
    contents of the inputs and therefore does not leak information about
    where two strings differ. Used wherever a client-supplied value is
    compared against a stored value outside of bcrypt's own comparison
    (which is already constant-time).

    Returns False for non-string inputs rather than raising, so a
    malformed value from an untrusted source cannot crash a verification
    path.
    """
    if not isinstance(a, str) or not isinstance(b, str):
        return False
    return secrets.compare_digest(a, b)


# ---------------------------------------------------------------------------
# JWT access tokens
# ---------------------------------------------------------------------------
_SAFE_ALGORITHMS = frozenset({
    "HS256", "HS384", "HS512",   # HMAC + shared secret (this app's default)
    "RS256", "RS384", "RS512",   # RSA + key pair (if you migrate)
    "ES256", "ES384", "ES512",   # ECDSA + key pair
})


def _validate_algorithm(alg: Optional[str]) -> str:
    """Pure validation of a JWT algorithm name.

    Extracted from the previous import-time-only validator so it can be
    unit-tested directly, without reimporting the module under a patched
    settings object. Behavior is identical: an empty or missing value and
    any value outside the allowlist raise; the value is returned
    uppercased and stripped.

    `'none'` is explicitly rejected because it would disable signature
    verification entirely - the classic `alg: none` attack.
    """
    candidate = (alg or "").strip().upper()
    if not candidate:
        raise RuntimeError(
            "settings.jwt_algorithm is empty. Set it to HS256 (default for "
            "this deployment's symmetric-secret scheme)."
        )
    if candidate not in _SAFE_ALGORITHMS:
        raise RuntimeError(
            f"settings.jwt_algorithm is {candidate!r}, which is not in the "
            f"allowlist {sorted(_SAFE_ALGORITHMS)}. The value 'none' is "
            "never acceptable - it disables signature verification."
        )
    if candidate.startswith(("RS", "ES")):
        logger.warning(
            "JWT algorithm is asymmetric (%s). Ensure jwt_secret_key is a "
            "PEM-encoded key, not an HMAC secret.", candidate,
        )
    return candidate


def _validate_algorithm_at_import() -> str:
    """Backwards-compatible wrapper preserved for any importer that
    referenced the previous name. Delegates to `_validate_algorithm`."""
    return _validate_algorithm(getattr(settings, "jwt_algorithm", None))


# Resolved once at import; every call to create/decode uses this value.
_JWT_ALGORITHM = _validate_algorithm_at_import()


def create_access_token(
    user_id: str,
    expires_minutes: Optional[int] = None,
) -> str:
    """Issue a signed access token for `user_id`.

    Adds `iat` (issued-at) and `jti` (unique token id) alongside the
    required `sub` and `exp`. Both are additive - tokens minted before
    this change (with only `sub` and `exp`) still decode successfully
    under decode_access_token because neither claim is required on read.
    """
    if not isinstance(user_id, str) or not user_id:
        raise ValueError("user_id must be a non-empty string")

    if expires_minutes is None:
        expires_minutes = settings.access_token_expire_minutes

    now = datetime.now(timezone.utc)
    payload = {
        "sub": user_id,
        "iat": now,
        "exp": now + timedelta(minutes=expires_minutes),
        "jti": uuid.uuid4().hex,
    }
    return jwt.encode(payload, settings.jwt_secret_key, algorithm=_JWT_ALGORITHM)


def decode_access_token(token: str) -> Optional[str]:
    """Return the token's `sub` claim if the token is valid, unexpired,
    and well-formed; otherwise None. Never raises.

    Enforcement:
      - Signature must verify under `_JWT_ALGORITHM` (never read from the
        token header - PyJWT's `algorithms=[...]` allowlist prevents both
        `alg: none` and RSA/HMAC confusion).
      - `exp` must be present and unexpired.
      - `sub` must be a non-empty string.
    """
    if not isinstance(token, str) or not token:
        return None

    try:
        payload = jwt.decode(
            token,
            settings.jwt_secret_key,
            algorithms=[_JWT_ALGORITHM],
            options={
                "require": ["exp"],
                "verify_signature": True,
            },
        )
    except jwt.PyJWTError as e:
        logger.debug("JWT rejected", reason=type(e).__name__)
        return None
    except Exception as e:  # noqa: BLE001 - any decode failure is a rejection
        logger.warning("Unexpected JWT decode error", reason=type(e).__name__)
        return None

    sub = payload.get("sub")
    if not isinstance(sub, str) or not sub:
        return None
    return sub